name: Actions

on:
  push:
    branches:
      - production

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  publish:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 'current'
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM dependencies
        run: npm install
        working-directory: .

      - name: Bump package version
        run: npx @helperkits/bumper bump
        working-directory: .

      - name: Build package
        run: npm run build
        working-directory: .

      - name: Publish package to NPM
        run: pwd && ls -la && npm publish --access public
        working-directory: ../eslint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}